version: '3.7'

services:
  web:
    build: .
    command: "./app -store postgres"
    ports:
      - 8080:8080
    depends_on:
      - db 
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
